export const CONN_SEQUENCES = {
  api: [
    { delay: 0, text: "$ anomalyiq connect --type rest --auth bearer", color: "#a8d8a8" },
    { delay: 320, text: "  Résolution DNS…", color: "#94a3b8" },
    { delay: 700, text: "  Ouverture connexion HTTPS…", color: "#94a3b8" },
    { delay: 1050, text: "  Authentification Bearer token…", color: "#94a3b8" },
    { delay: 1400, text: "  ✔ Connexion établie", color: "#4ade80" },
    { delay: 1700, text: "  Découverte des endpoints…", color: "#94a3b8" },
    { delay: 2100, text: "  ✔ Schéma récupéré — 8 champs détectés", color: "#4ade80" },
    { delay: 2400, text: "__FIELDS__", color: "#60a5fa" },
    { delay: 2800, text: "  ✔ Test d'import (50 enregistrements)…", color: "#94a3b8" },
    { delay: 3200, text: "__ROWS__", color: "#f9a8d4" },
    { delay: 3600, text: "  ✔ Connexion API opérationnelle", color: "#4ade80" },
    { delay: 3900, text: "  Pipeline prêt pour l'analyse ML →", color: "#fbbf24" },
  ],
  jdbc: [
    { delay: 0, text: "$ anomalyiq connect --type jdbc --driver postgres", color: "#a8d8a8" },
    { delay: 320, text: "  Résolution hôte…", color: "#94a3b8" },
    { delay: 700, text: "  Connexion TCP port 5432…", color: "#94a3b8" },
    { delay: 1050, text: "  Authentification SQL…", color: "#94a3b8" },
    { delay: 1400, text: "  ✔ Connexion base de données établie", color: "#4ade80" },
    { delay: 1700, text: "  Introspection du schéma…", color: "#94a3b8" },
    { delay: 2100, text: "  ✔ Tables et colonnes récupérées", color: "#4ade80" },
    { delay: 2400, text: "__FIELDS__", color: "#60a5fa" },
    { delay: 2800, text: "  Échantillon de données (100 lignes)…", color: "#94a3b8" },
    { delay: 3200, text: "__ROWS__", color: "#f9a8d4" },
    { delay: 3600, text: "  ✔ Base de données opérationnelle", color: "#4ade80" },
    { delay: 3900, text: "  Pipeline prêt pour l'analyse ML →", color: "#fbbf24" },
  ],
  sftp: [
    { delay: 0, text: "$ anomalyiq connect --type sftp --port 22", color: "#a8d8a8" },
    { delay: 320, text: "  Résolution hôte SFTP…", color: "#94a3b8" },
    { delay: 700, text: "  Handshake SSH…", color: "#94a3b8" },
    { delay: 1050, text: "  Authentification…", color: "#94a3b8" },
    { delay: 1400, text: "  ✔ Session SFTP ouverte", color: "#4ade80" },
    { delay: 1700, text: "  Listage du répertoire…", color: "#94a3b8" },
    { delay: 2100, text: "  ✔ Fichiers CSV détectés", color: "#4ade80" },
    { delay: 2400, text: "__FIELDS__", color: "#60a5fa" },
    { delay: 2800, text: "  Lecture partielle (preview)…", color: "#94a3b8" },
    { delay: 3200, text: "__ROWS__", color: "#f9a8d4" },
    { delay: 3600, text: "  ✔ Source SFTP opérationnelle", color: "#4ade80" },
    { delay: 3900, text: "  Pipeline prêt pour l'analyse ML →", color: "#fbbf24" },
  ],
  csv: [
    { delay: 0, text: "$ anomalyiq import --source csv --validate", color: "#a8d8a8" },
    { delay: 320, text: "  Lecture du fichier…", color: "#94a3b8" },
    { delay: 700, text: "  Parsing en-têtes CSV…", color: "#94a3b8" },
    { delay: 1100, text: "  ✔ En-têtes détectés :", color: "#4ade80" },
    { delay: 1350, text: "__FIELDS__", color: "#60a5fa" },
    { delay: 1700, text: "  Validation des types…", color: "#94a3b8" },
    { delay: 2100, text: "  ✔ Colonnes montant   → numeric (float64)", color: "#4ade80" },
    { delay: 2400, text: "  ✔ Colonnes date      → datetime", color: "#4ade80" },
    { delay: 2700, text: "  ✔ Colonnes fournisseur → string", color: "#4ade80" },
    { delay: 3000, text: "  Chargement dans la mémoire pipeline…", color: "#94a3b8" },
    { delay: 3400, text: "__ROWS__", color: "#f9a8d4" },
    { delay: 3800, text: "  ✔ Import terminé avec succès", color: "#4ade80" },
    { delay: 4000, text: "  Pipeline prêt — analyse ML disponible →", color: "#fbbf24" },
  ],
};

export function getDefaultFields(connType, csvDetectedFields = []) {
  const defaults = {
    api: ["invoice_ref", "invoice_date", "amount", "supplier_code", "label", "entity", "status", "due_date"],
    jdbc: ["invoice_id", "date_facture", "montant_ttc", "code_fournisseur", "libelle", "entite", "statut", "echeance"],
    sftp: ["ref_facture", "date", "montant", "fournisseur", "service", "societe", "statut", "date_echeance"],
    csv: csvDetectedFields.length > 0 ? csvDetectedFields : ["invoice_ref", "invoice_date", "amount", "supplier_code", "label", "entity", "status", "due_date"],
  };
  return defaults[connType] || defaults.api;
}
